#!/bin/bash

set -euo pipefail
#set -x

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

main()
{
    run_command="$1"
    submission="$2"
    results=${SCRIPT_DIR}/results.json

    rm -fv ${results}


    ${SCRIPT_DIR}/do_run.sh \
	 --command ${run_command} \
	 --submission "${submission}" \
	 --results-file "${results}" || rv=$?

    if [[ -e ${results} ]]; then
	cat ${results} | jq
    fi
}

main $@
